### ISSUE TITLE
Why is the tail sampling less in CBEffectNumSampler, shouldn't the tail sampling be increased?

### ISSUE THREAD

**Issue by empty2enrich** [Keke921/GCLLoss#1]
I have some doubts about this？looking forward to your reply

**Comment by Keke921** [comment]
Since the first stage increases the sample validity of the tail class. We thind this operation can increase the "effective number" of tail classes. 
And the tail sampling rate is still higher compared to head classes. It is less than the original effective number sampling rate. 
The first stage has made the model pay more attention to the tail classes, and the second stage should reduces the sampling rate of the tail class compared with the original effective number sampling. 
Hope it can solve your doubts

**Comment by empty2enrich** [comment]
> Since the first stage increases the sample validity of the tail class. We thind this operation can increase the "effective number" of tail classes. And the tail sampling rate is still higher compared to head classes. It is less than the original effective number sampling rate. The first stage has made the model pay more attention to the tail classes, and the second stage should reduces the sampling rate of the tail class compared with the original effective number sampling. Hope it can solve your doubts

Thanks!
If I don't train in two stages, the backbone classifier is trained together. Which sampler is better to use? BalancedRS? EffectNumRS?

**Comment by Keke921** [comment]
> > Since the first stage increases the sample validity of the tail class. We thind this operation can increase the "effective number" of tail classes. And the tail sampling rate is still higher compared to head classes. It is less than the original effective number sampling rate. The first stage has made the model pay more attention to the tail classes, and the second stage should reduces the sampling rate of the tail class compared with the original effective number sampling. Hope it can solve your doubts
> 
> Thanks! If I don't train in two stages, the backbone classifier is trained together. Which sampler is better to use? BalancedRS? EffectNumRS?

To be honest, I don't think they'll be significantly different. Various balanced sampling methods will reduce the performance of the head classes. May be CBEffectNumSampler will perform better, because it won't reduce the performance too much on head classes. But the parameter 'beta_a' in the sampler needs to be adjusted. I think it will surely be worse than the two-stage training. Sorry I didn't verify. Just an intuitive guess.

**Comment by empty2enrich** [comment]
> > > Since the first stage increases the sample validity of the tail class. We thind this operation can increase the "effective number" of tail classes. And the tail sampling rate is still higher compared to head classes. It is less than the original effective number sampling rate. The first stage has made the model pay more attention to the tail classes, and the second stage should reduces the sampling rate of the tail class compared with the original effective number sampling. Hope it can solve your doubts
> > 
> > 
> > Thanks! If I don't train in two stages, the backbone classifier is trained together. Which sampler is better to use? BalancedRS? EffectNumRS?
> 
> To be honest, I don't think they'll be significantly different. Various balanced sampling methods will reduce the performance of the head classes. May be CBEffectNumSampler will perform better, because it won't reduce the performance too much on head classes. But the parameter 'beta_a' in the sampler needs to be adjusted. I think it will surely be worse than the two-stage training. Sorry I didn't verify. Just an intuitive guess.

Ok, I see
thanks for your reply.
